objects/BlueBerryEvent__c.object
<CustomObject>
    <fields>
        <fullName>BlueBerryVenue__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Venue</label>
        <referenceTo>BlueBerryVenue__c</referenceTo>
        <relationshipLabel>Venue Details</relationshipLabel>
        <relationshipName>BlueBerryEvents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <label>Event Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>BlueBerryEvent</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BlueBerryEvents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BlueBerryEventRegistration__c.object
<CustomObject>
    <fields>
        <fullName>BlueBerryEvent__c</fullName>
        <label>Event Name</label>
        <referenceTo>BlueBerryEvent__c</referenceTo>
        <relationshipLabel>BlueBerryEventRegistrations</relationshipLabel>
        <relationshipName>BlueBerryEventRegistrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BlueBerrySession__c</fullName>
        <label>Session Name</label>
        <referenceTo>BlueBerrySession__c</referenceTo>
        <relationshipLabel>Registered List</relationshipLabel>
        <relationshipName>BlueBerryEventRegistrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Event Attendee List</relationshipLabel>
        <relationshipName>BlueBerryEventRegistrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BlueBerryEventRegistration</label>
    <nameField>
        <displayFormat>REG#{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BlueBerryEventRegistrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BlueBerrySession__c.object
<CustomObject>
    <fields>
        <fullName>BlueBerryEvent__c</fullName>
        <label>Event Name</label>
        <referenceTo>BlueBerryEvent__c</referenceTo>
        <relationshipLabel>BlueBerrySessions</relationshipLabel>
        <relationshipName>BlueBerrySessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session_Capacity__c</fullName>
        <label>Session Capacity</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Registration__c</fullName>
        <label>Total Registration</label>
        <summaryForeignKey>BlueBerryEventRegistration__c.BlueBerrySession__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>BlueBerrySession</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BlueBerrySessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BlueBerryVenue__c.object
<CustomObject>
    <description>Custom table to store Venue details containing Venue Name, Address, Phone and Capacity</description>
    <label>BlueBerryVenue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BlueBerryVenues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BBEvent_Registration_Contorller.cls
public class BBEvent_Registration_Contorller {
    public BlueBerryEventRegistration__c newregistration;
    public List<BlueBerrySession__c> sessionList;
    public List<BlueBerryEvent__c> eventRecordList;
    public String firstName{get;set;}
    public String lastName{get;set;}
    public String registerEmail{get;set;}
    //public Boolean isAvailable {get;set;}
    public String eventRecord;
    public string selectedSession{get;set;}
    public List<SelectOption> sessionOptionsList{ get;set; }
    public Id contactId;
    //public String registrationid{get;set;}
    public Date tempdate;
    public  String eventStartDateParam;
    public  String eventVenueParam;
    public String duplicateRecord{get;set;} 
    public BBEvent_Registration_Contorller(){
        
    }
    public void pageload(){
        eventRecord = Apexpages.currentPage().getParameters().get('eventRecordId');
        
        eventRecordList = [select id,Name,Event_Start_Date__c,BlueBerryVenue__r.Name,(select Id,Name,session_capacity__C,Total_registration__C from BlueBerrySessions__r) from BlueBerryEvent__c where id =:eventRecord];
        if(!eventRecordList.isEmpty()){
            sessionList= eventRecordList[0].BlueBerrySessions__r;
            tempdate = eventRecordList[0].Event_Start_Date__c;
            eventStartDateParam = String.valueOf(tempdate.month())+'/'+String.valueOf(tempdate.day())+'/'+String.valueOf(tempdate.year());
            eventVenueParam  = eventRecordList[0].BlueBerryVenue__r.Name;
            system.debug('eventStartDateParam :'+eventStartDateParam);
        }
//        System.debug('\nSmith-BBEvent_Registration_Contorller in method pageload : \neventListId='+eventRecord+'\n eventStartDateParam :'+eventStartDateParam+'\n eventVenueParam :'+eventVenueParam);
        newregistration = new BlueBerryEventRegistration__c();
        
        sessionOptionsList = new list<SelectOption>();
        //sessionOptionsList.add(new SelectOption('----SelectOption------','----SelectOption------'));
        for (BlueBerrySession__c temp : sessionList)
        {
            if(temp.session_capacity__C > temp.Total_registration__C)
            sessionOptionsList.add(new SelectOption(temp.Id,temp.Name));
        }
    }
    
    public PageReference completeRegistration(){
        List<Contact> contactlist = [Select id,Email from Contact where Email=:registerEmail];
        if(contactlist.isEmpty()){
            Account newAccount = new Account(Name=firstName);
            insert newAccount;
            Contact newcontact = new Contact();
            newcontact.AccountId=newAccount.Id;
            newcontact.FirstName=firstName;
            newcontact.LastName=lastName;
            newcontact.Email=registerEmail;
            insert newcontact;
            contactId = newcontact.Id;          
        }
        else{
            contactId=contactlist[0].Id;
        }

        BlueBerryEventRegistration__c bookAttendee = new BlueBerryEventRegistration__c();
        bookAttendee.BlueBerryEvent__c = Id.valueOf(eventRecord);
        bookAttendee.Contact__c = Id.valueOf(contactId);
        bookAttendee.BlueBerrySession__c = Id.valueOf(selectedSession);
        Database.SaveResult registration = Database.insert(bookAttendee,false);
        if (registration.isSuccess())
        {
            PageReference tosuccesspage = Page.BB_REGISTRATION_SUCCESS;
            tosuccesspage.getParameters().put('eventStartDateParam',eventStartDateParam);
            tosuccesspage.getParameters().put('eventVenueParam',eventVenueParam);
            tosuccesspage.setRedirect(false);
            return tosuccesspage;    
        }
        else{
            duplicateRecord = '';             
            for(Database.Error err : registration.getErrors())
            {
                duplicateRecord += (err.getMessage() + '  ');
                //duplicateRecord = 'Oops! Event already registered with the given Email ID. Please Note Event registration is allowed only once  irrespective of Session';
            }
            ApexPages.Message duplicateRecords= new ApexPages.Message(ApexPages.Severity.INFO, duplicateRecord);
            ApexPages.addMessage(duplicateRecords);  
            return null; 
        }
    }
  
}