objects/BlueBerryEvent__c.object
<CustomObject>
    <fields>
        <fullName>Available_Sessions__c</fullName>
        <label>Available Sessions</label>
        <summaryForeignKey>BlueBerrySession__c.BlueBerryEvent__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>BlueBerryVenue__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Venue</label>
        <referenceTo>BlueBerryVenue__c</referenceTo>
        <relationshipLabel>Venue Details</relationshipLabel>
        <relationshipName>BlueBerryEvents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Capacity__c</fullName>
        <label>Event Capacity</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Due_Date__c</fullName>
        <label>Event Due Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <label>Event Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BlueBerryEvent</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BlueBerryEvents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BlueBerryVenue__c.object
<CustomObject>
    <description>Custom table to store Venue details containing Venue Name, Address, Phone and Capacity</description>
    <fields>
        <fullName>VenueAddress__c</fullName>
        <label>VenueAddress</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue_Contact__c</fullName>
        <label>Venue Contact</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>BlueBerryVenue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BlueBerryVenues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BBC_Events_List.cls
public class BBC_Events_List { 
    public List<BlueBerryEvent__c> eventList {get;set;}
    public String eventRecordId {get;set;}
    public BBC_Events_List(){
        eventList =  [Select id,Name, Event_Start_Date__c,Event_Due_Date__c,Available_Sessions__c,Event_Capacity__c,BlueBerryVenue__c,BlueBerryVenue__r.Name,BlueBerryVenue__r.VenueAddress__c,BlueBerryVenue__r.Venue_Contact__c from BlueBerryEvent__c where Status__c='Active' and Event_Due_Date__c > TODAY order by Event_Start_Date__c desc]; 
    }

    public PageReference RegisterForm(){
        PageReference toregisterform = Page.BB_REGISTER_FORM;
        toregisterform.getParameters().put('eventRecordId',eventRecordId);
        toregisterform.setRedirect(true);
        return toregisterform;
    }
    
}