objects/Invoice__c.object
<CustomObject>
    <description>Exercise 2</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This field is used to identify the status of the Invoice.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Pending review</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Invoice__c</fullName>
        <description>Sum of total invoice value</description>
        <inlineHelpText>Sum of total invoice value</inlineHelpText>
        <label>Total Invoice</label>
        <summarizedField>Line_Item__c.Total_cost__c</summarizedField>
        <summaryForeignKey>Line_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>triggerupdatefield__c</fullName>
        <description>trigger update field</description>
        <label>triggerupdatefield</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inovices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Line_Item__c.object
<CustomObject>
    <description>Line Items custom object</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <description>Invoice for master detail relationship</description>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Merchandise__c</fullName>
        <label>Merchandise</label>
        <referenceTo>smith__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_cost__c</fullName>
        <description>Total cost incurred</description>
        <formula>Quantity__c  *  Unit_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>product of Unitcost and currency</inlineHelpText>
        <label>Total cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unti price</description>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InvoiceActionController.cls
public class InvoiceActionController{
    
    public InvoiceActionController(){
        inv=[select name,total_invoice__c,status__c,triggerupdatefield__c from Invoice__c where name='IN-0005'];
    }
    
    Public Invoice__c inv {get;set;}
    public String smith1 {get;set;}
    Public String inputvalue1 {get;set;}
    
    public PageReference invoiceaction(){
        System.debug('stage 1'+ smith1);
        
        inputvalue1=smith1;
        
        smith1=null;
        System.debug('stage 1'+ smith1);
        Long startingTime = System.now().getTime(); // Num milliseconds since Jan 1 1970
        Integer delayInMilliseconds = 1500; // One-second delay
        while (System.now().getTime() - startingTime < delayInMilliseconds)  {
            // Do nothing until desired delay has passed
        }
      //  PageReference finalreults = new PageReference("$resource.finalreults");
      //  
      System.debug('Before executing');
		inv = [select Name,Status__c,Total_Invoice__c,triggerupdatefield__c from Invoice__c where Name = :inputvalue1];
        
        //System.debug('{!inv}');
      	List <Line_Item__c> litm = [Select Name,Merchandise__c,Quantity__c,Total_cost__c,Unit_Price__c 
                                    from Line_Item__c where Invoice__c = :inv.Id ];
        
    //  PageReference testpage = Page.finalreults;
//testpage.setRedirect(false);
//return OpenNewPage;
        //return testpage;
        return null;
        
    }
    //inputvalue1=smith;
    public PageReference returnpage(){
    /*    //public Invoice__c inv3 {get;set;}
        //public List <Line_Item__c> litm3 {get;set;}
PageReference returnpage = Page.InvoiceActionpage;
        returnpage.setredirect(true);
        return returnpage;*/
        return null;
    }

}