objects/Invoice__c.object
<CustomObject>
    <description>Exercise 2</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This field is used to identify the status of the Invoice.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Pending review</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Invoice__c</fullName>
        <description>Sum of total invoice value</description>
        <inlineHelpText>Sum of total invoice value</inlineHelpText>
        <label>Total Invoice</label>
        <summarizedField>Line_Item__c.Total_cost__c</summarizedField>
        <summaryForeignKey>Line_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>triggerupdatefield__c</fullName>
        <description>trigger update field</description>
        <label>triggerupdatefield</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inovices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Line_Item__c.object
<CustomObject>
    <description>Line Items custom object</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <description>Invoice for master detail relationship</description>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LineAfterTrigger__c</fullName>
        <label>LineAfterTrigger</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LineBeforeTrigger__c</fullName>
        <label>LineBeforeTrigger</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestingClass.cls
public with sharing class TestingClass {

    public Invoice__c inv{get;set;}
    //public Line_Item__C litm{get;set;}
    public TestingClass(){
       // inv=[select name,total_invoice__c,status__c,triggerupdatefield__c from Invoice__c where name='IN-0005'];
    }
   
    public static void triggertesting(Invoice__c[] invoice){
        List <Id> invid = new List <Id>();
        
        for (Invoice__c inv : invoice){
            if(inv.Status__c=='closed'){
            invid.add(inv.id);
            inv.triggerupdatefield__C='beforeupdatetrigger'+ System.now();}
        }
system.debug('place1');
            //if (inv.name=='IN-0005')
            
            
            List <Line_Item__c> litm = [select linebeforetrigger__c, lineaftertrigger__c from Line_item__c where invoice__c in :invid];
            for (Line_item__c Linetm : litm){
       system.debug('place2'); 
                
                linetm.linebeforetrigger__c='BeforeUpdateTrigger'+ System.now();
                linetm.lineaftertrigger__c='AfterUpdateTrigger'+ System.now();
            }
            update litm;
        }  
 
    
    public static void cloneattachment (Attachment[] newattach){
        List <Id> listid = new List<Id>();
//        Attachment[] newcreatedattach = new Attachment();
        for (Attachment tempattach : newattach)
        {
            listid.add(Id.valueof(tempattach.Name)); 
        }
        Attachment[] oldattach = [select ID,NAME,DESCRIPTION,BODY FROM ATTACHMENT WHERE ID IN :listid];
        for (Attachment newtemploop : newattach){
            for (Attachment oldtemploop : oldattach){
                if(newtemploop.Name==oldtemploop.id){
                    newtemploop.NAME=oldtemploop.NAME;
                    newtemploop.BODY=oldtemploop.BODY;
                    newtemploop.DESCRIPTION=oldtemploop.DESCRIPTION;

                }
            }
        }
        //insert newattach;
    }
        
    
}